language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t kotinephew/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true kotinephew/docker-react npm run test -- --coverage
  


